# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_key', models.CharField(max_length=100, unique=True)),
                ('configuration_description', models.TextField(blank=True, verbose_name='a brief description of this setting')),
            ],
        ),
    ]
