# Generated by Django 2.0.4 on 2018-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_status', models.CharField(choices=[('RQ', 'Requested'), ('AP', 'Approved'), ('CO', 'Completed'), ('FA', 'Failed')], default='RQ', max_length=2)),
                ('query_title', models.CharField(max_length=50)),
                ('query', models.TextField()),
                ('query_result', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_key', models.CharField(max_length=100, unique=True)),
                ('configuration_value', models.TextField()),
                ('configuration_description', models.TextField(blank=True, verbose_name='a brief description of this setting')),
            ],
            options={
                'ordering': ['configuration_key'],
            },
        ),
        migrations.CreateModel(
            name='MasterDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_status', models.CharField(choices=[('ST', 'Staged'), ('CO', 'Completed'), ('FA', 'Failed')], default='ST', max_length=2)),
                ('commit_title', models.CharField(max_length=50)),
                ('deploy_result', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['tag_name'],
            },
        ),
    ]
