# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='configuration_value',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
