# Generated by Django 2.0.4 on 2018-05-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseRefresh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_status', models.CharField(choices=[('ST', 'Staged'), ('SU', 'Success'), ('BF', 'Backup Failed'), ('SF', 'Sync Failed')], default='ST', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.DateTimeField(null=True)),
            ],
        ),
    ]
