# Generated by Django 2.0.4 on 2018-05-27 12:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_databaserefresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='notify_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
        migrations.AddField(
            model_name='tag',
            name='notify_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
