# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_configuration_configuration_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ['configuration_key']},
        ),
    ]
