# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_status', models.CharField(choices=[('RQ', 'Requested'), ('AP', 'Approved'), ('CO', 'Completed'), ('FA', 'Failed')], default='RQ', max_length=2)),
                ('query_title', models.CharField(max_length=50)),
                ('query', models.TextField()),
                ('query_result', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.DateTimeField(null=True)),
            ],
        ),
    ]
