# Generated by Django 2.0.4 on 2018-06-02 06:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20180601_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminquery',
            name='notify_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='notify_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
    ]
