# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-13 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_adminquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deploy_status', models.CharField(choices=[('ST', 'Staged'), ('CO', 'Completed'), ('FA', 'Failed')], default='ST', max_length=2)),
                ('commit_title', models.CharField(max_length=50)),
                ('deploy_result', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('executed', models.DateTimeField(null=True)),
            ],
        ),
    ]
