# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardProgramCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=100)),
                ('program_count', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
    ]
