# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardSectorCoordinators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('centers', models.CharField(max_length=1500)),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
    ]
