# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_ircdashboardsectorcoordinators'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardMissingRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('center_name', models.CharField(max_length=100)),
                ('role_level', models.CharField(max_length=25)),
                ('available_roles', models.CharField(max_length=2000)),
                ('missing_roles', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['zone_name', 'center_name'],
            },
        ),
    ]
