# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_ircdashboardmissingroles'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardZoneSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('center_count', models.IntegerField()),
                ('teacher_count', models.IntegerField()),
                ('program_count', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
    ]
