# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_ircdashboardzonesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ircdashboardprogramcounts',
            name='program_window',
            field=models.CharField(default='past', max_length=10),
            preserve_default=False,
        ),
    ]
