# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_ircdashboardprogramcounts_program_window'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardRoleSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('role_name', models.CharField(max_length=100)),
                ('role_count', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name', 'role_name'],
            },
        ),
    ]
