# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_ircdashboardrolesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardCenterMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('center_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('recent_program_count', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name', 'center_name'],
            },
        ),
    ]
