# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_ircdashboardcentermap'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRCDashboardCenterMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('center_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name', 'center_name'],
            },
        ),
    ]
