# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-06 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_ircdashboardcentermaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ircdashboardcentermaterial',
            options={'ordering': ['zone_name', 'center_name', 'item_name']},
        ),
    ]
