# Generated by Django 2.0.4 on 2018-05-04 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_title', models.CharField(max_length=100)),
                ('notify_status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Draft', max_length=10)),
                ('notify_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], default='Email', max_length=10)),
                ('sending_mode', models.CharField(choices=[('Classic', 'Classic'), ('Individual', 'Individual'), ('BCC', 'BCC')], default='Classic', max_length=10)),
                ('notify_from', models.CharField(max_length=100)),
                ('notify_to', models.TextField(blank=True)),
                ('notify_cc', models.TextField(blank=True)),
                ('zones', models.TextField(blank=True)),
                ('centers', models.TextField(blank=True)),
                ('roles', models.TextField(blank=True)),
                ('message', models.TextField()),
                ('detailed_status', models.TextField(blank=True)),
                ('delete_attachments', models.BooleanField(default=True, verbose_name='Delete attachments after send')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NotifyAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='notifications/')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.Notifier')),
            ],
        ),
        migrations.CreateModel(
            name='NotifyContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_title', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='notifier',
            name='notify_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notify.NotifyContext'),
        ),
    ]
