# Generated by Django 2.0.4 on 2018-05-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifier',
            name='centers',
        ),
    ]
