# Generated by Django 2.0.4 on 2018-05-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_notifier_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='sending_mode',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Individual', 'Individual')], default='Classic', max_length=10),
        ),
    ]
