# Generated by Django 2.0.4 on 2018-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20180514_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifier',
            name='notify_title',
            field=models.CharField(max_length=200),
        ),
    ]
