# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0011_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('program_type', models.CharField(blank=True, choices=[('NONE', 'Please Select'), ('IP', 'Introductory Programs'), ('AP', 'Advanced Programs'), ('RP', 'Rejuvenation Programs'), ('CP', 'Childrens Programs'), ('SS', 'Sadhgurus Schedule'), ('SP', 'Special Events & Other Programs')], default='NONE', max_length=4)),
                ('language_type', models.CharField(blank=True, choices=[('NONE', 'Please Select'), ('TM', 'Tamil'), ('EG', 'English'), ('HI', 'Hindi'), ('BI', 'bilingual'), ('CH', 'Chinese')], default='NONE', max_length=4)),
                ('description', django_markdown.models.MarkdownField(blank=True)),
            ],
            options={
                'ordering': ['name', 'program_type'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end Date')),
                ('donation', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('teacher_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='teacher Name')),
                ('coteacher_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='co-teacher Name')),
                ('online_registration', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=2, null=True)),
                ('session_details', models.CharField(default='6.0.6', max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='contact Name')),
                ('contact_phone1', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone1')),
                ('contact_phone2', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone2')),
                ('contact_email', models.EmailField(default='xyz@gmail.com', max_length=50, verbose_name='contact Email')),
                ('status', models.CharField(blank=True, choices=[('NW', 'New'), ('RO', 'Registration Open'), ('RC', 'Registration Close'), ('CA', 'Cancelled'), ('CO', 'Closed'), ('PE', 'Preponed'), ('PO', 'Postponed')], default='Y', max_length=2, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_markdown.models.MarkdownField(max_length=500)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
            ],
            options={
                'verbose_name': 'Intro Session Detail',
            },
        ),
        migrations.CreateModel(
            name='VenueAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('address_line_3', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='contact number for this address')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
            ],
        ),
    ]
