# Generated by Django 2.0.4 on 2018-05-01 07:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batch_code', models.CharField(max_length=2)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Batch Master',
            },
        ),
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Language Master',
            },
        ),
        migrations.CreateModel(
            name='ProgramAdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='title')),
                ('value', models.TextField(verbose_name='information')),
            ],
            options={
                'verbose_name': 'additional program information. (Do not use if not required)',
            },
        ),
        migrations.CreateModel(
            name='ProgramAdditionalLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.LanguageMaster')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('end_time', models.CharField(blank=True, max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.BatchMaster')),
            ],
            options={
                'verbose_name': 'Program Batch',
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Program Categories',
                'ordering': ['name'],
                'verbose_name': 'Program Category',
            },
        ),
        migrations.CreateModel(
            name='ProgramCountMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_category', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['count_category'],
                'verbose_name': 'program count type',
            },
        ),
        migrations.CreateModel(
            name='ProgramMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('abbreviation', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Program Master',
            },
        ),
        migrations.CreateModel(
            name='ProgramMasterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramCategory')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster')),
            ],
            options={
                'ordering': ['program', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProgramReceiptAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_count', models.IntegerField(default=0)),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramCountMaster')),
            ],
            options={
                'verbose_name': 'program receipt counts',
            },
        ),
        migrations.CreateModel(
            name='ProgramSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('program_location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('BO', 'All'), ('M', 'Gents'), ('F', 'Ladies')], default='BO', max_length=2)),
                ('start_date', models.DateField(verbose_name='Program Start Date')),
                ('end_date', models.DateField(verbose_name='Program End Date')),
                ('donation_amount', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('event_management_software', models.CharField(blank=True, max_length=15)),
                ('event_management_code', models.CharField(blank=True, max_length=15, verbose_name='ORS Code')),
                ('online_registration', models.BooleanField(default=True)),
                ('online_registration_code', models.CharField(blank=True, max_length=15, verbose_name='joomla Code')),
                ('contact_name', models.CharField(max_length=50, verbose_name='contact Name')),
                ('contact_phone1', models.CharField(max_length=15, verbose_name='Contact Phone1')),
                ('contact_phone2', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone2')),
                ('contact_email', models.EmailField(max_length=50, verbose_name='contact Email')),
                ('status', models.CharField(choices=[('RO', 'Registration Open'), ('RC', 'Registration Closed'), ('CA', 'Cancelled'), ('CO', 'Closed')], default='RO', max_length=2)),
                ('receipts', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('cancelled_date', models.DateField(null=True)),
                ('center', smart_selects.db_fields.GroupedForeignKey(group_field='zone', on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('primary_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.LanguageMaster')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster')),
            ],
            options={
                'ordering': ['-start_date', 'center'],
                'verbose_name': 'Program Schedule',
            },
        ),
        migrations.CreateModel(
            name='ProgramScheduleCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramCountMaster')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
            ],
            options={
                'verbose_name': 'program count',
            },
        ),
        migrations.CreateModel(
            name='ProgramScheduleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_timestamp', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
            ],
            options={
                'verbose_name_plural': 'notes about program',
                'ordering': ['-note_timestamp'],
                'verbose_name': 'program note',
            },
        ),
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Tag')),
            ],
            options={
                'ordering': ['program', 'tag'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(blank=True, choices=[('MO', 'Morning'), ('NO', 'Noon'), ('EV', 'Evening'), ('MN', 'Morning and Noon'), ('ME', 'Morning and Evening'), ('NE', 'Noon and Evening'), ('AL', 'Morning, Noon and Evening'), ('FD', 'Full Day')], max_length=2, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
            options={
                'verbose_name_plural': 'teachers for class',
                'verbose_name': 'teacher for class',
            },
        ),
        migrations.CreateModel(
            name='ProgramVenueAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('address_line_3', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='contact number for this address')),
                ('contact_email', models.EmailField(blank=True, max_length=100, verbose_name='email for this address')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
            ],
            options={
                'verbose_name_plural': 'venue addresses',
                'verbose_name': 'venue address',
            },
        ),
        migrations.AddField(
            model_name='programreceiptamounts',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programbatch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programadditionallanguages',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programadditionalinformation',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AlterUniqueTogether(
            name='programteacher',
            unique_together={('program', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='programtag',
            unique_together={('program', 'tag')},
        ),
        migrations.AlterUniqueTogether(
            name='programschedulecounts',
            unique_together={('program', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='programreceiptamounts',
            unique_together={('program', 'category')},
        ),
    ]
