# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 06:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_merge'),
        ('schedulemaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Batch Master',
            },
        ),
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Language Master',
            },
        ),
        migrations.CreateModel(
            name='ProgramBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('end_time', models.TimeField(blank=True, max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.BatchMaster')),
            ],
            options={
                'verbose_name': 'Program Batch',
            },
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('display', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Program Category',
            },
        ),
        migrations.CreateModel(
            name='ProgramCounts',
            fields=[
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='schedulemaster.ProgramSchedule')),
                ('introduction_count', models.IntegerField(default=0)),
                ('registered_count', models.IntegerField(default=0)),
                ('morning_count', models.IntegerField(default=0)),
                ('noon_count', models.IntegerField(default=0)),
                ('evening_count', models.IntegerField(default=0)),
                ('absentees_count', models.IntegerField(default=0)),
                ('volunteers_count', models.IntegerField(default=0)),
                ('initiation_volunteers_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Program Details',
            },
        ),
        migrations.CreateModel(
            name='ProgramMasterCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramCategory')),
            ],
            options={
                'ordering': ['program', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProgramScheduleNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'notes about program',
                'verbose_name': 'a program note',
            },
        ),
        migrations.CreateModel(
            name='ProgramTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(blank=True, choices=[('MT', 'Main Teacher'), ('CT', 'Co-Teacher'), ('OT', 'Observation Teacher')], default='MT', max_length=2, null=True)),
            ],
            options={
                'verbose_name_plural': 'teachers for class',
                'verbose_name': 'teacher for class',
            },
        ),
        migrations.CreateModel(
            name='ProgramVenueAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(max_length=100)),
                ('address_line_3', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('contact_number', models.CharField(blank=True, max_length=15, verbose_name='contact number for this address')),
            ],
            options={
                'verbose_name_plural': 'venue addresses',
                'verbose_name': 'venue address',
            },
        ),
        migrations.RemoveField(
            model_name='schedulenote',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='venueaddress',
            name='schedule',
        ),
        migrations.AlterModelOptions(
            name='programmaster',
            options={'ordering': ['name'], 'verbose_name': 'Program Master'},
        ),
        migrations.AlterModelOptions(
            name='programschedule',
            options={'ordering': ['-start_date', 'center'], 'verbose_name': 'Program Schedule'},
        ),
        migrations.RemoveField(
            model_name='programmaster',
            name='language_type',
        ),
        migrations.RemoveField(
            model_name='programmaster',
            name='program_type',
        ),
        migrations.RemoveField(
            model_name='programschedule',
            name='coteacher_name',
        ),
        migrations.RemoveField(
            model_name='programschedule',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='programschedule',
            name='session_details',
        ),
        migrations.RemoveField(
            model_name='programschedule',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='programmaster',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Active'), ('IA', 'In-Active')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='donation_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programschedule',
            name='event_management_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='code from event management software'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='online_registration_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='program_location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='contact_email',
            field=models.EmailField(max_length=50, verbose_name='contact Email'),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='contact_name',
            field=models.CharField(default='', max_length=50, verbose_name='contact Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='contact_phone1',
            field=models.CharField(max_length=15, verbose_name='Contact Phone1'),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='end_date',
            field=models.DateField(default=datetime.date(2016, 2, 8), verbose_name='end Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='online_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='start_date',
            field=models.DateField(default=datetime.date(2016, 2, 8), verbose_name='start Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='status',
            field=models.CharField(choices=[('RO', 'Registration Open'), ('AN', 'Announced'), ('RC', 'Registration Closed'), ('CA', 'Cancelled'), ('CO', 'Closed')], default='RO', max_length=2),
        ),
        migrations.DeleteModel(
            name='ScheduleNote',
        ),
        migrations.DeleteModel(
            name='VenueAddress',
        ),
        migrations.AddField(
            model_name='programvenueaddress',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programteacher',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='programschedulenote',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programmastercategory',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster'),
        ),
        migrations.AddField(
            model_name='programbatch',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='programschedule',
            name='language',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.LanguageMaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programschedule',
            name='second_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_language', to='schedulemaster.LanguageMaster'),
        ),
    ]
