# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0003_auto_20160208_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programschedulecounts',
            options={'verbose_name': 'program count'},
        ),
        migrations.RenameField(
            model_name='programschedulecounts',
            old_name='count',
            new_name='value',
        ),
    ]
