# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0004_auto_20160208_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmaster',
            name='status',
        ),
        migrations.AddField(
            model_name='programmaster',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
