# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0005_auto_20160208_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='programvenueaddress',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='email for this address'),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='second_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_language', to='schedulemaster.LanguageMaster'),
        ),
    ]
