# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0006_auto_20160208_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchmaster',
            name='batch_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
