# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0007_batchmaster_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='batch_code',
            field=models.CharField(max_length=2),
        ),
    ]
