# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0009_auto_20160411_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='gender',
            field=models.CharField(choices=[('BO', 'All'), ('M', 'Gents'), ('F', 'Ladies')], default='BO', max_length=2),
        ),
    ]
