# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 05:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0010_auto_20160411_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programschedulenote',
            options={'ordering': ['-note_timestamp'], 'verbose_name': 'program note', 'verbose_name_plural': 'notes about program'},
        ),
        migrations.AddField(
            model_name='programschedulenote',
            name='note_timestamp',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2016, 4, 17, 11, 20, 28, 465895)),
            preserve_default=False,
        ),
    ]
