# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-17 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0011_auto_20160417_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedulenote',
            name='note_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
