# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0012_auto_20160417_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
