# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0013_programschedule_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmaster',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
