# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-07 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0014_programmaster_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='event_management_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='ORS Code'),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='online_registration_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='joomla Code'),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='status',
            field=models.CharField(choices=[('RO', 'Registration Open'), ('RC', 'Registration Closed'), ('CA', 'Cancelled'), ('CO', 'Closed')], default='RO', max_length=2),
        ),
    ]
