# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0015_auto_20160707_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 12, 1, 17, 57, 716508)),
            preserve_default=False,
        ),
    ]
