# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0016_programschedule_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='cancelled_date',
            field=models.DateField(null=True),
        ),
    ]
