# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_tag'),
        ('schedulemaster', '0017_programschedule_cancelled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Tag')),
            ],
            options={
                'ordering': ['program', 'tag'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='programtag',
            unique_together=set([('program', 'tag')]),
        ),
    ]
