# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0018_auto_20161007_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programbatch',
            unique_together=set([('program', 'batch')]),
        ),
        migrations.AlterUniqueTogether(
            name='programschedulecounts',
            unique_together=set([('program', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='programteacher',
            unique_together=set([('program', 'teacher')]),
        ),
    ]
