# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0019_auto_20161007_2137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programbatch',
            unique_together=set([]),
        ),
    ]
