# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0020_auto_20161007_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='event_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
