# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0023_auto_20170530_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmaster',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
