# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-28 10:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0024_programmaster_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='programschedule',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 27, 0, 0)),
            preserve_default=False,
        ),
    ]
