# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0025_programschedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programteacher',
            name='teacher_type',
            field=models.CharField(blank=True, choices=[('MO', 'Morning'), ('NO', 'Noon'), ('EV', 'Evening'), ('MN', 'Morning and Noon'), ('ME', 'Morning and Evening'), ('NE', 'Noon and Evening'), ('AL', 'Morning, Noon and Evening'), ('FD', 'Full Day')], max_length=2, null=True),
        ),
    ]
