# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-24 07:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0028_auto_20171223_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramReceiptAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_count', models.IntegerField(default=0)),
                ('receipt_amout', models.DecimalField(decimal_places=2, max_digits=9)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramCountMaster')),
            ],
            options={
                'verbose_name': 'program receipt counts',
            },
        ),
        migrations.AddField(
            model_name='programschedule',
            name='receipts',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programreceiptamounts',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AlterUniqueTogether(
            name='programreceiptamounts',
            unique_together=set([('program', 'category')]),
        ),
    ]
