# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0029_auto_20180124_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programreceiptamounts',
            old_name='receipt_amout',
            new_name='receipt_amount',
        ),
    ]
