# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0030_auto_20180127_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='end_date',
            field=models.DateField(verbose_name='Program End Date'),
        ),
        migrations.AlterField(
            model_name='programschedule',
            name='start_date',
            field=models.DateField(verbose_name='Program Start Date'),
        ),
    ]
