# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0031_auto_20180328_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='languagemaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programcountmaster',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programmaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='programschedulenote',
            name='note',
            field=models.TextField(),
        ),
    ]
