#!/bin/bash
# 26-May-2017, add this to repo to maintain audit trail

source /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/aasaan_backup_db
source /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/aasaan_backup_metabase
python /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/database_backup_clean.py

DJANGODIR=/home/deepak/django/aasaan/aasaan
DJANGO_SETTINGS_MODULE=aasaan.settings.prod

# Activate the virtual environment
cd $DJANGODIR
source /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# database cleanup queries go here

# the below is a temporary query written to clean off orphan entries in the schedulemaster_programteacher
# table. it interferes with enrollments sync. until a permenant fix is done
# Deepak - 6-Jan-2017, Saturday
docker exec -it aasaan_db psql -U aasaan -c "delete from schedulemaster_programteacher where teacher_id is null"

# 29-Jul-2018, temp comment out until Joomla issue is fixed
python manage.py create_joomla_programs
python manage.py create_ors_programs
python manage.py close_past_programs
python manage.py sync_ors_counts
python manage.py sync_joomla_counts
python manage.py sync_ereceipts
python manage.py sync_ereceipt_amounts

docker exec aasaan_db psql -U aasaan -c "REFRESH MATERIALIZED VIEW SCHEDULE_SNAPSHOT"
docker exec aasaan_db psql -U aasaan -c "VACUUM FULL VERBOSE ANALYZE"

# run dropbox for 10 minutes so everything is synced
docker start dropbox
sleep 10m
docker stop dropbox

python manage.py notify_program_creation
python manage.py notify_program_cancellation
python manage.py sync_iyc_schedules
python manage.py sync_sheets
#python manage.py sync_contacts

# copy latest sql into docker container for postgres
docker cp /home/deepak/django/aasaan/sql/voucher_tracking_snapshot_teachers.sql aasaan_db:/tmp
docker cp /home/deepak/django/aasaan/sql/voucher_tracking_snapshot.sql aasaan_db:/tmp

docker exec aasaan_db psql -U aasaan -d aasaan -t -A -f /tmp/voucher_tracking_snapshot.sql > /var/www/aasaan/media/ipcaccounts/vouchers/vouchers.json
docker exec aasaan_db psql -U aasaan -d aasaan -t -A -f /tmp/voucher_tracking_snapshot_teachers.sql > /var/www/aasaan/media/ipcaccounts/vouchers/vouchers_teachers.json

# restart metabase container
docker restart metabase
