#!/bin/bash

cd /home/deepak/django/aasaan
git pull
/home/deepak/django/aasaan/.virtualenvs/aasaan/bin/pip install -r requirements.txt

DJANGODIR=/home/deepak/django/aasaan/aasaan
DJANGO_SETTINGS_MODULE=aasaan.settings.prod

# Activate the virtual environment
cd $DJANGODIR
source /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

python manage.py migrate
python manage.py collectstatic --no-input

cd /home/deepak/django/aasaan/deploy

cp aasaan_sync_sheets ~/.virtualenvs/aasaan/bin
cp aasaan_hourly_cron ~/.virtualenvs/aasaan/bin
cp aasaan_worker_start ~/.virtualenvs/aasaan/bin
cp aasaan_backup_db ~/.virtualenvs/aasaan/bin
cp aasaan_backup_metabase ~/.virtualenvs/aasaan/bin
cp database_backup_clean.py ~/.virtualenvs/aasaan/bin
cp aasaan_deploy ~/.virtualenvs/aasaan/bin
cp gunicorn_start ~/.virtualenvs/aasaan/bin
chmod +x ~/.virtualenvs/aasaan/bin/aasaan_sync_sheets
chmod +x ~/.virtualenvs/aasaan/bin/aasaan_hourly_cron
chmod +x ~/.virtualenvs/aasaan/bin/aasaan_worker_start
chmod +x ~/.virtualenvs/aasaan/bin/aasaan_backup_db
chmod +x ~/.virtualenvs/aasaan/bin/aasaan_backup_metabase
chmod +x ~/.virtualenvs/aasaan/bin/aasaan_deploy
chmod +x ~/.virtualenvs/aasaan/bin/gunicorn_start

sudo restart_aasaan


