#!/bin/bash

NAME="aasaan"                                  # Name of the application
DJANGODIR=/usr/aasaan/src/aasaan       # Django project directory
USER=root                                       # the user to run as
GROUP=root                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=aasaan.settings.prod-docker             # which settings file should Django use
DJANGO_WSGI_MODULE=aasaan.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

python manage.py migrate --settings=aasaan.settings.prod-docker
python manage.py collectstatic --no-input --settings=aasaan.settings.prod-docker

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /usr/local/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=aasaan:8001 \
  --log-file=-
  --log-level=debug \
  --log-file=-
