#!/bin/bash

# cron to run every 15 minutes for management tasks

DJANGODIR=/home/deepak/django/aasaan/aasaan
DJANGO_SETTINGS_MODULE=aasaan.settings.prod

# Activate the virtual environment
cd $DJANGODIR
source /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

docker exec aasaan_db psql -U aasaan -c "REFRESH MATERIALIZED VIEW VOUCHER_SNAPSHOT"

python manage.py dispatch_staged_communications
python manage.py run_admin_queries
python manage.py deploy_master_changes
python manage.py refresh_database
