#!/bin/bash

BACKUP_DIR=/home/deepak/dropbox/aasaan/database-backups
WORKING_DIR=$(mktemp -d)
TODAY=$(date +\%Y-\%m-\%d)
BACKUP_FILE_BASE=aasaan_db_$TODAY.dat
BACKUP_FILE=${WORKING_DIR}/${BACKUP_FILE_BASE}
docker exec aasaan_db pg_dump -U aasaan -d aasaan > $BACKUP_FILE
BACKUP_FILE_ARCHIVE=${BACKUP_FILE}.gz
tar -czf ${BACKUP_FILE_ARCHIVE} ${BACKUP_FILE}
rm ${BACKUP_FILE}
rm -rf ${BACKUP_DIR}/${BACKUP_FILE_BASE}.gz
mv ${BACKUP_FILE_ARCHIVE} ${BACKUP_DIR}
rm -rf ${WORKING_DIR}
