#!/bin/bash

NAME="aasaan"                                  # Name of the application
DJANGODIR=/home/deepak/django/aasaan/aasaan       # Django project directory
SOCKFILE=/home/deepak/django/aasaan/run/gunicorn.sock # we will communicte using this unix socket
USER=aasaan                                       # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=aasaan.settings.prod             # which settings file should Django use
DJANGO_WSGI_MODULE=aasaan.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/deepak/django/aasaan/.virtualenvs/aasaan/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-