# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 08:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('AasaanUser', '0003_aasaanusercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aasaanusercenter',
            name='center',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='zone', on_delete=django.db.models.deletion.CASCADE, to='contacts.Center'),
        ),
    ]
