# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 09:33
from __future__ import unicode_literals

import brochures.models
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0019_auto_20160424_1149'),
        ('schedulemaster', '0014_programmaster_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(blank=True, max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('brochure_image', models.ImageField(blank=True, upload_to=brochures.models._brochure_image_path)),
                ('description', models.TextField(blank=True)),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.LanguageMaster')),
            ],
            options={
                'verbose_name': 'Program Material Master',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Brochures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('ACTV', 'Active'), ('DMGD', 'Damaged'), ('LOST', 'Lost')], default='ACTV', max_length=6)),
                ('brochure_image', models.CharField(blank=True, max_length=250)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochureMaster')),
            ],
            options={
                'verbose_name': 'Program Material',
                'verbose_name_plural': 'Program Materials',
            },
        ),
        migrations.CreateModel(
            name='BrochureSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster')),
            ],
            options={
                'verbose_name': 'Program Material Set',
                'verbose_name_plural': 'Program Material Sets',
            },
        ),
        migrations.CreateModel(
            name='BrochureSetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('brochure_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochureSet')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochureMaster')),
            ],
        ),
        migrations.CreateModel(
            name='BrochuresShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_from', models.CharField(blank=True, max_length=50)),
                ('sent_to', models.CharField(blank=True, max_length=50)),
                ('sent_date', models.DateField(blank=True)),
                ('received_date', models.DateField(blank=True)),
                ('courier_vendor', models.CharField(blank=True, max_length=50)),
                ('courier_no', models.CharField(blank=True, max_length=50)),
                ('courier_status', models.CharField(blank=True, choices=[('CS', 'Courier Sent'), ('NEW', 'Not Initiated'), ('CR', 'Received'), ('IT', 'In Transit')], default='NEW', max_length=3)),
                ('remarks', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Material Shipment',
                'ordering': ['sent_date'],
            },
        ),
        migrations.CreateModel(
            name='BrochuresTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'Transfer Initiated'), ('DD', 'Sent / Received'), ('TC', 'Cancelled'), ('LOST', 'Lost/Damaged')], default='NEW', max_length=6)),
                ('source_printer', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('transaction_status', models.CharField(blank=True, default='NEW', max_length=15, null=True)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('brochure_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochureSet')),
                ('destination_program_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_sch', to='schedulemaster.ProgramSchedule')),
            ],
            options={
                'verbose_name': 'Program Material Transaction',
                'verbose_name_plural': 'Program Material Transactions',
            },
        ),
        migrations.CreateModel(
            name='BrochuresTransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_quantity', models.IntegerField(verbose_name='quantity')),
                ('received_quantity', models.IntegerField(blank=True, null=True)),
                ('brochures_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochuresTransaction')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochureMaster')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='BroucherTransferNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_timestamp', models.DateTimeField(auto_now_add=True)),
                ('brochure_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochuresTransaction')),
            ],
            options={
                'verbose_name': 'Transaction note',
                'verbose_name_plural': 'Transaction notes',
                'ordering': ['-note_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockPointAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
                ('contact_number1', models.CharField(blank=True, max_length=15, verbose_name='contact Number1')),
                ('contact_number2', models.CharField(blank=True, max_length=15, verbose_name='contact Number2')),
            ],
        ),
        migrations.CreateModel(
            name='StockPointMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stock Point Incharge')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact No')),
                ('contact_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone')),
            ],
            options={
                'verbose_name': 'Stock Point Master',
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockPointNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('note_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock Point & Materials note',
                'verbose_name_plural': 'notes about Stock Point & Materials',
                'ordering': ['-note_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTypeMaster',
            fields=[
                ('value', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TransactionType Master',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockpointaddress',
            name='stock_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.StockPointMaster'),
        ),
        migrations.AddField(
            model_name='brochurestransaction',
            name='destination_stock_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_sp', to='brochures.StockPointMaster'),
        ),
        migrations.AddField(
            model_name='brochurestransaction',
            name='source_stock_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brochures.StockPointMaster'),
        ),
        migrations.AddField(
            model_name='brochurestransaction',
            name='transfer_type',
            field=models.ForeignKey(default='SPSP', null=True, on_delete=django.db.models.deletion.CASCADE, to='brochures.TransactionTypeMaster'),
        ),
        migrations.AddField(
            model_name='brochurestransaction',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone'),
        ),
        migrations.AddField(
            model_name='brochuresshipment',
            name='brochures_transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.BrochuresTransaction'),
        ),
        migrations.AddField(
            model_name='brochures',
            name='stock_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.StockPointMaster'),
        ),
        migrations.CreateModel(
            name='StockPoint',
            fields=[
            ],
            options={
                'verbose_name': 'Materials in Stock Point',
                'proxy': True,
            },
            bases=('brochures.stockpointmaster',),
        ),
        migrations.AddField(
            model_name='stockpointnote',
            name='stock_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brochures.StockPoint'),
        ),
        migrations.AlterUniqueTogether(
            name='brochuremaster',
            unique_together=set([('name', 'version', 'language')]),
        ),
    ]
