# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brochures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuremaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='brouchertransfernote',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stockpointnote',
            name='note',
            field=models.TextField(),
        ),
    ]
