# Generated by Django 2.0.4 on 2018-05-01 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipcaccounts', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=100, verbose_name='From')),
                ('destination', models.CharField(default='', max_length=100, verbose_name='To')),
                ('onward_date', models.DateField(default=datetime.date.today, verbose_name='Date of Journey')),
                ('travel_mode', models.CharField(choices=[('TR', 'Train'), ('BS', 'Bus'), ('FL', 'Flight')], default='TR', max_length=2)),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('IP', 'In-Progress'), ('BK', 'Booked'), ('VC', 'Voucher Created'), ('CL', 'Cancelled'), ('PD', 'Processed')], default='IP', max_length=2)),
                ('email_sent', models.BooleanField(default=False)),
                ('invoice_no', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoice/%Y/%m/%d/')),
                ('booked_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Booked Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ManyToManyField(blank=True, to='contacts.Contact')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone')),
            ],
            options={
                'ordering': ['onward_date'],
                'verbose_name': 'Travel Request',
            },
        ),
    ]
