# Generated by Django 2.0.4 on 2018-04-13 15:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'Traveller',
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=100, verbose_name='From')),
                ('destination', models.CharField(default='', max_length=100, verbose_name='To')),
                ('onward_date', models.DateField(default=datetime.date.today, verbose_name='Date of Journey')),
                ('travel_mode', models.CharField(choices=[('TR', 'Train'), ('BS', 'Bus'), ('FL', 'Flight')], default='TR', max_length=2)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('IP', 'In-Progress'), ('BK', 'Booked'), ('CL', 'Cancelled'), ('PD', 'Processed')], default='IP', max_length=2)),
                ('email_sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Travel Request',
                'ordering': ['onward_date'],
            },
        ),
        migrations.AddField(
            model_name='travellers',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.TravelRequest'),
        ),
    ]
