# Generated by Django 2.0.5 on 2018-05-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='teacher',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
    ]
