# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='zone',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone'),
            preserve_default=False,
        ),
    ]
