# Generated by Django 2.0.4 on 2018-04-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travellers',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='travellers',
            name='travel_request',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='teacher',
            field=models.ManyToManyField(to='contacts.Contact'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='remarks',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Remarks'),
        ),
        migrations.DeleteModel(
            name='Travellers',
        ),
    ]
