# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 12:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0002_auto_20180410_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelrequest',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='travelrequest',
            name='_to',
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='destination',
            field=models.CharField(default='', max_length=100, verbose_name='To'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='source',
            field=models.CharField(default='', max_length=100, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='onward_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of Journey'),
        ),
    ]
