# Generated by Django 2.0.4 on 2018-05-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20180503_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('IP', 'In-Progress'), ('BK', 'Booked'), ('VC', 'Voucher Created'), ('CL', 'Cancelled'), ('CB', 'Cancel Booked Ticket'), ('PD', 'Processed')], default='IP', max_length=2),
        ),
    ]
