# Generated by Django 2.0.4 on 2018-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20180425_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='attachments',
            field=models.FileField(default='', null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
