# Generated by Django 2.0.4 on 2018-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_travelrequest_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
    ]
