# Generated by Django 2.0.4 on 2018-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20180425_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('IP', 'In-Progress'), ('BK', 'Booked'), ('VC', 'Voucher Created'), ('CL', 'Cancelled'), ('PD', 'Processed')], default='IP', max_length=2),
        ),
    ]
