# Generated by Django 2.0.4 on 2018-05-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_auto_20180507_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='onward_date',
            field=models.DateTimeField(verbose_name='Date of Journey'),
        ),
    ]
