# Generated by Django 2.0.4 on 2018-04-27 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0001_initial'),
        ('travels', '0005_auto_20180426_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster'),
        ),
    ]
