# Generated by Django 2.0.4 on 2018-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0005_auto_20180509_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='travel_class',
            field=models.CharField(choices=[('Train', ((1, 'Sleeper / 2S'), (2, '2 AC'), (3, '3 AC / Chair Car'))), ('Bus', ((4, 'Sleeper'), (5, 'Semi Sleeper'))), ('Flight', ((6, 'Economy'), (7, 'Business')))], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
