# Generated by Django 2.0.4 on 2018-04-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_travelrequest_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='booked_date',
            field=models.DateField(blank=True, null=True, verbose_name='Booked Date'),
        ),
    ]
