# Generated by Django 2.0.4 on 2018-05-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0006_travelrequest_travel_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='travel_class',
            field=models.CharField(choices=[('Train', (('1', 'SL'), ('2', '2 AC'), ('3', '3 AC'), ('4', '2S'), ('5', 'Chair Car'))), ('Bus', (('6', 'Sleeper Non AC'), ('7', 'Semi Sleeper AC'), ('10', 'Semi Sleeper Non AC'), ('11', 'Semi Sleeper AC'))), ('Flight', (('8', 'Economy'), ('9', 'Business')))], max_length=2),
        ),
    ]
