# Generated by Django 2.0.4 on 2018-04-27 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_travelrequest_booked_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='booked_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Booked Date'),
        ),
    ]
