# Generated by Django 2.0.4 on 2018-05-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_auto_20180510_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Travel Note',
            },
        ),
        migrations.CreateModel(
            name='AgentTravelRequest',
            fields=[
            ],
            options={
                'verbose_name': 'IPC Teachers Travel Request',
                'indexes': [],
                'proxy': True,
            },
            bases=('travels.travelrequest',),
        ),
        migrations.CreateModel(
            name='TrTravelRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Travel Request',
                'indexes': [],
                'proxy': True,
            },
            bases=('travels.travelrequest',),
        ),
        migrations.AlterModelOptions(
            name='travelrequest',
            options={'ordering': ['onward_date'], 'verbose_name': 'Teacher Travel Request'},
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('IP', 'Initiated'), ('BO', 'Book the Ticket'), ('BK', 'Booked'), ('VC', 'Voucher Created'), ('CL', 'Cancelled'), ('CB', 'Cancel Booked Ticket'), ('PD', 'Processed')], default='IP', max_length=2),
        ),
        migrations.AddField(
            model_name='travelnotes',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.TravelRequest'),
        ),
    ]
