# Generated by Django 2.0.4 on 2018-06-07 07:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_auto_20180515_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='notify_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='notify_toggle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='status',
            field=models.CharField(choices=[('IP', 'Requested'), ('BO', 'Approved'), ('BK', 'Booked'), ('VC', 'Voucher Created'), ('CL', 'Cancelled'), ('CB', 'Booked Ticket Cancelled'), ('PD', 'Voucher Processed')], default='IP', max_length=2),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='travel_class',
            field=models.CharField(choices=[('Train', (('1', 'SL'), ('2', '2 AC'), ('3', '3 AC'), ('4', '2S'), ('5', 'Chair Car'))), ('Bus', (('6', 'Sleeper Non AC'), ('7', 'Sleeper AC'), ('10', 'Semi Sleeper Non AC'), ('11', 'Semi Sleeper AC'))), ('Flight', (('8', 'Economy'), ('9', 'Business')))], max_length=2),
        ),
    ]
