# Generated by Django 2.0.5 on 2018-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion
import travels.models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_auto_20180607_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_multiple', models.ImageField(blank=True, null=True, upload_to='teacher_travels/%Y/%m/%d/', validators=[travels.models.Attachment.validate_image], verbose_name='Upload image file')),
            ],
            options={
                'ordering': ['event'],
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='full Name')),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='Mobile Number')),
            ],
            options={
                'ordering': ['full_name'],
                'verbose_name': 'Others detail',
            },
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='is_others',
            field=models.BooleanField(default=False, verbose_name='Others'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='teacher',
            field=models.ManyToManyField(blank=True, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='others',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.TravelRequest'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.TravelRequest'),
        ),
    ]
