# Generated by Django 2.0.4 on 2018-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0012_auto_20180924_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='others',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
    ]
