# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0023_center_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter_name', models.CharField(max_length=50)),
                ('submitter_mobile', models.CharField(max_length=10)),
                ('event_category', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Educational Instituations', 'Educational Instituations'), ('Corporate', 'Corporate'), ('Government', 'Government'), ('Religious', 'Religious'), ('Other', 'Other')], max_length=50)),
                ('event_name', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('people_category', models.CharField(choices=[('Isha Meditator', 'Isha Meditator'), ('General Public', 'General Public'), ('Devotees', 'Devotees'), ('Corporate', 'Corporate'), ('Students', 'Students'), ('VIPs', 'VIPs'), ('Other', 'Other')], max_length=50)),
                ('event_details', models.TextField()),
                ('isha_aspect', models.CharField(max_length=100)),
                ('event_start_date', models.DateField()),
                ('event_end_date', models.DateField()),
                ('event_timing', models.CharField(max_length=20)),
                ('event_entry_category', models.CharField(choices=[('Free', 'Free'), ('Walk In', 'Walk In'), ('RSVP', 'RSVP'), ('Paid Registration', 'Paid Registration'), ('By Invite Only', 'By Invite Only')], max_length=50)),
                ('event_url', models.URLField(max_length=100)),
                ('ashram_contact_name', models.CharField(max_length=50)),
                ('ashram_contact_mobile', models.CharField(max_length=10)),
                ('final_remarks', models.TextField()),
                ('admin_approved', models.BooleanField(default=False)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone')),
            ],
            options={
                'ordering': ['zone', 'center', '-event_start_date', 'event_name'],
            },
        ),
    ]
