# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-13 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localevents',
            name='event_url',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='localevents',
            name='final_remarks',
            field=models.TextField(blank=True),
        ),
    ]
