# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Error', 'Error')], default='Pending', max_length=25)),
                ('communication_title', models.CharField(blank=True, max_length=100)),
                ('communication_type', models.CharField(blank=True, choices=[('EMail', 'EMail'), ('SMS', 'SMS')], default='EMail', max_length=15)),
                ('communication_context', models.CharField(choices=[('Communication', 'Planned Communication'), ('Transaction', 'Transactional Communication')], default='Communication', max_length=15)),
                ('communication_date', models.DateField(auto_now_add=True)),
                ('communication_hash', models.CharField(max_length=100)),
                ('communication_notes', models.TextField()),
                ('communication_message', models.TextField()),
            ],
            options={
                'ordering': ['-communication_date', 'communication_title'],
            },
        ),
        migrations.CreateModel(
            name='PayloadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Error', 'Error')], default='Pending', max_length=25)),
                ('communication_recipient', models.CharField(max_length=100)),
                ('communication_send_time', models.DateTimeField(null=True)),
                ('communication_status_message', models.TextField(blank=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Payload')),
            ],
            options={
                'ordering': ['communication', 'communication_recipient'],
            },
        ),
    ]
