# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100, verbose_name="name to display in the 'From' field")),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.SmallIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False, verbose_name='use this as default profile?')),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
