# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20160202_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_visibility', models.CharField(choices=[('BCC', 'All recipients in BCC'), ('TO/BCC', 'First recipient in "To", others in BCC'), ('Individual', 'Send individual email to all (Slower)')], default='BCC', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
