# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_auto_20160203_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsetting',
            name='recipient_visibility',
            field=models.CharField(choices=[('BCC', 'All recipients in BCC'), ('TO/CC', 'First recipient in "To", others in CC'), ('TO/BCC', 'First recipient in "To", others in BCC'), ('Individual', 'Send individual email to all (Slower)')], default='BCC', max_length=10),
        ),
    ]
