# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_auto_20160203_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendGridProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=100, verbose_name="name to display in the 'From' field")),
                ('from_email', models.EmailField(max_length=100, verbose_name='from email address')),
                ('api_key', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False, verbose_name='use this as default profile?')),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_type',
            field=models.CharField(blank=True, choices=[('EMail', 'EMail'), ('SMS', 'SMS'), ('SendGrid', 'SendGrid')], default='EMail', max_length=15),
        ),
    ]
