# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_auto_20160208_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('EMail', 'EMail'), ('SMS', 'SMS'), ('SendGrid', 'SendGrid')], default='EMail', max_length=25)),
                ('profile_name', models.CharField(max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='sender name to use')),
                ('sender_id', models.CharField(blank=True, max_length=100, verbose_name='from email or ID to use')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name or API key')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='password (if applicable)')),
                ('smtp_server', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='SMTP server address (for email only)')),
                ('smtp_port', models.SmallIntegerField(default=587, verbose_name='SMTP port (for email only)')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS settings (email only)')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL settings (email only)')),
                ('default', models.BooleanField(default=False, verbose_name='use this as default profile?')),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailProfile',
        ),
        migrations.DeleteModel(
            name='EmailSetting',
        ),
        migrations.DeleteModel(
            name='SendGridProfile',
        ),
        migrations.AddField(
            model_name='payload',
            name='communication_status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='recipient_visibility',
            field=models.CharField(blank='', choices=[('BCC', 'All recipients in BCC'), ('TO/CC', 'First recipient in "To", others in CC'), ('TO/BCC', 'First recipient in "To", others in BCC'), ('Individual', 'Send individual email to all (Slower)')], default='BCC', max_length=20, verbose_name='recipient visibility (applies only to email profiles)'),
        ),
        migrations.AlterField(
            model_name='payloaddetail',
            name='communication_status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='communicationprofile',
            unique_together=set([('communication_type', 'profile_name')]),
        ),
    ]
