# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_auto_20160215_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationprofile',
            name='communication_type',
            field=models.CharField(choices=[('EMail', 'EMail'), ('SMS', 'SMS'), ('SendGrid', 'SendGrid'), ('Pushover', 'Pushover')], default='EMail', max_length=25),
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_type',
            field=models.CharField(blank=True, choices=[('EMail', 'EMail'), ('SMS', 'SMS'), ('SendGrid', 'SendGrid'), ('Pushover', 'Pushover')], default='EMail', max_length=15),
        ),
    ]
