# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-11 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_auto_20160726_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payload',
            name='communication_context',
            field=models.CharField(choices=[('Communication', 'Planned Communication'), ('Transactional', 'Transactional Communication')], default='Communication', max_length=15),
        ),
    ]
