# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_auto_20160912_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationprofile',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payload',
            name='communication_status_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payloaddetail',
            name='communication_status_message',
            field=models.TextField(blank=True),
        ),
    ]
