from django import forms

class LocalEventsForm(forms.Form):
    zone = forms.CharField(max_length=100)
    center = forms.CharField(max_length=100)
    submitter_name = forms.CharField(max_length=50)
    submitter_mobile = forms.CharField(max_length=10)
    event_category = forms.CharField(max_length=50)
    event_name = forms.CharField(max_length=100)
    number_of_people = forms.IntegerField()
    people_category = forms.CharField(max_length=50)
    event_details = forms.CharField()
    isha_aspect = forms.CharField(max_length=100)
    event_start_date = forms.DateField()
    event_end_date = forms.DateField(required=False)
    event_timing = forms.CharField(max_length=20)
    event_venue = forms.CharField(max_length=100)
    event_city = forms.CharField(max_length=50)
    event_entry_category = forms.CharField(max_length=50)
    event_organizer_contact = forms.CharField(max_length=25)
    event_url = forms.URLField(max_length=100, required=False)
    ashram_contact_name = forms.CharField(max_length=50)
    ashram_contact_mobile = forms.CharField(max_length=10)
    final_remarks = forms.CharField(required=False)
