# Generated by Django 2.0.4 on 2018-06-27 10:57

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import servicedesk.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_remove_contact_id_proof_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_multiple', models.ImageField(blank=True, null=True, upload_to='service_request/%Y/%m/%d/', validators=[servicedesk.models.Attachment.validate_image], verbose_name='Upload image file')),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='IPCSystemMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_toggle', models.BooleanField(default=False)),
                ('notify_meta', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('priority', models.CharField(choices=[('ME', 'Mediaum'), ('HI', 'High'), ('Low', 'Low'), ('UR', 'Urgent')], default='ME', max_length=2)),
                ('expected_date', models.DateField(verbose_name='Expected Date')),
                ('exp_resolved_date', models.DateField(verbose_name='Expected Resolve Date')),
                ('resolved_date', models.DateField(verbose_name='Resolve Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('center', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='zone', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Service Desk',
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.ServiceRequest')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Service Note',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.ServiceStatusMaster', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.IPCSystemMaster', verbose_name='IPC Systems'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.ServiceRequest'),
        ),
        migrations.CreateModel(
            name='IPCServiceRequest',
            fields=[
            ],
            options={
                'verbose_name': 'IPC Service Desk',
                'indexes': [],
                'proxy': True,
            },
            bases=('servicedesk.servicerequest',),
        ),
    ]
