# Generated by Django 2.0.4 on 2018-06-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='exp_resolved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expected Resolve Date'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='priority',
            field=models.CharField(choices=[('ME', 'Medium'), ('HI', 'High'), ('Low', 'Low'), ('UR', 'Urgent')], default='ME', max_length=2),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='resolved_date',
            field=models.DateField(blank=True, null=True, verbose_name='Actual Resolve Date'),
        ),
    ]
