# Generated by Django 2.0.4 on 2018-06-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0002_auto_20180627_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipcservicerequest',
            options={'verbose_name': 'IPC Service Desk', 'verbose_name_plural': 'IPC Service Desk'},
        ),
        migrations.AlterModelOptions(
            name='ipcsystemmaster',
            options={'verbose_name': 'IPC System Master', 'verbose_name_plural': 'IPC System Master'},
        ),
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created'], 'verbose_name': 'Service Desk', 'verbose_name_plural': 'Service Desk'},
        ),
        migrations.AlterModelOptions(
            name='servicestatusmaster',
            options={'verbose_name': 'Service Status Master', 'verbose_name_plural': 'Service Status Master'},
        ),
    ]
