# Generated by Django 2.0.4 on 2018-07-13 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicedesk', '0003_auto_20180627_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcsystemmaster',
            name='assigned_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='system_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicedesk.IPCSystemMaster', verbose_name='Service Request'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
