# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OverseasEnrollement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('center_name', models.CharField(blank=True, max_length=100, null=True)),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_day', models.IntegerField(blank=True, null=True)),
                ('total_participants', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('co_teacher', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsProgramCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=100)),
                ('program_window', models.CharField(max_length=10)),
                ('participant_count', models.IntegerField()),
                ('program_count', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('program_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_full_time', models.IntegerField(blank=True, null=True)),
                ('no_of_part_time', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UyirNokkamEnrollement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_classes', models.IntegerField(blank=True, null=True)),
                ('no_of_participant', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
