# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsProgramCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=100)),
                ('program_window', models.CharField(max_length=10)),
                ('program_count', models.IntegerField()),
            ],
            options={
                'ordering': ['zone_name'],
            },
        ),
    ]
