# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-31 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsprogramcounts',
            name='participant_count',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
