# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-31 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uyirnokkamenrollement',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='uyirnokkamenrollement',
            name='start_date',
        ),
    ]
