# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0002_auto_20170131_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overseasenrollement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='overseasenrollement',
            name='start_date',
        ),
        migrations.AddField(
            model_name='overseasenrollement',
            name='program_month',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AddField(
            model_name='overseasenrollement',
            name='program_start_date',
            field=models.DateField(default='2017-01-01'),
        ),
        migrations.AlterField(
            model_name='overseasenrollement',
            name='center_name',
            field=models.CharField(default='IIIS', max_length=100),
        ),
        migrations.AlterField(
            model_name='overseasenrollement',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
        migrations.AlterField(
            model_name='overseasenrollement',
            name='program_name',
            field=models.CharField(default='4DTLIE', max_length=100),
        ),
        migrations.AlterField(
            model_name='overseasenrollement',
            name='total_participants',
            field=models.IntegerField(default=0),
        ),
    ]
