# Generated by Django 2.0.5 on 2018-06-14 07:08

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos_multiple', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/%d/', validators=[feedback.models.Photo.validate_image], verbose_name='Attachments')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
            ],
            options={
                'ordering': ['event'],
                'verbose_name': 'Attachment',
            },
        ),
    ]
