# Generated by Django 2.0.4 on 2018-04-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name_as_inid',
            field=models.CharField(blank=True, max_length=50, verbose_name='name as in id card'),
        ),
    ]
