# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
        ),
        migrations.AlterField(
            model_name='sector',
            name='sector_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
