# Generated by Django 2.0.4 on 2018-05-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id_card_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='id_card_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pushbullet_token',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pushover_token',
        ),
        migrations.AddField(
            model_name='contact',
            name='name_as_in_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name as in ID'),
        ),
    ]
