# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20151206_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='sector',
        ),
        migrations.AlterField(
            model_name='center',
            name='center_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='zone_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
