# Generated by Django 2.0.4 on 2018-05-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180507_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id_proof_other',
        ),
    ]
