# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20151206_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualContactRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['contact', 'role', 'center'],
            },
        ),
        migrations.CreateModel(
            name='IndividualRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('role_remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PCC Role',
                'ordering': ['role_name'],
            },
        ),
        migrations.RemoveField(
            model_name='contactcenter',
            name='center',
        ),
        migrations.RemoveField(
            model_name='contactcenter',
            name='contact',
        ),
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['center_name'], 'verbose_name': 'PCC Center'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_name'], 'verbose_name': 'PCC Role Group'},
        ),
        migrations.DeleteModel(
            name='ContactCenter',
        ),
        migrations.AddField(
            model_name='individualcontactrole',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center'),
        ),
        migrations.AddField(
            model_name='individualcontactrole',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='individualcontactrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.IndividualRole'),
        ),
    ]
