# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20151207_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualContactRoleSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
            options={
                'ordering': ['contact', 'role', 'sector'],
            },
        ),
        migrations.CreateModel(
            name='IndividualContactRoleZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
            ],
            options={
                'ordering': ['contact', 'role', 'zone'],
            },
        ),
        migrations.RenameModel(
            old_name='IndividualContactRole',
            new_name='IndividualContactRoleCenter',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='RoleGroup',
        ),
        migrations.RemoveField(
            model_name='contactzone',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactzone',
            name='zone',
        ),
        migrations.AddField(
            model_name='individualrole',
            name='role_level',
            field=models.CharField(choices=[('ZO', 'Zone'), ('SC', 'Sector'), ('CE', 'Center')], default='ZO', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContactZone',
        ),
        migrations.AddField(
            model_name='individualcontactrolezone',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.IndividualRole'),
        ),
        migrations.AddField(
            model_name='individualcontactrolezone',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone'),
        ),
        migrations.AddField(
            model_name='individualcontactrolesector',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.IndividualRole'),
        ),
        migrations.AddField(
            model_name='individualcontactrolesector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Sector'),
        ),
    ]
