# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20151208_2120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactRole',
            new_name='ContactRoleGroup',
        ),
    ]
