# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 11:07
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20151212_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=contacts.models._generate_profile_path),
        ),
    ]
