# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 07:17
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20151230_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=django_markdown.models.MarkdownField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='note',
            field=django_markdown.models.MarkdownField(max_length=500),
        ),
    ]
