# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20151231_1247'),
        ('contacts', '0009_auto_20160106_1637'),
    ]

    operations = [
    ]
