# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='pre_center',
            field=models.BooleanField(default=False),
        ),
    ]
