# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_center_pre_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='center',
            options={'ordering': ['center_name'], 'verbose_name': 'IPC Center'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'IPC Contact'},
        ),
        migrations.AlterModelOptions(
            name='individualcontactrolecenter',
            options={'ordering': ['contact', 'role', 'center'], 'verbose_name': 'IPC center level contact role'},
        ),
        migrations.AlterModelOptions(
            name='individualcontactrolesector',
            options={'ordering': ['contact', 'role', 'sector'], 'verbose_name': 'IPC sector level contact role'},
        ),
        migrations.AlterModelOptions(
            name='individualcontactrolezone',
            options={'ordering': ['contact', 'role', 'zone'], 'verbose_name': 'IPC zone level contact role'},
        ),
        migrations.AlterModelOptions(
            name='individualrole',
            options={'ordering': ['role_name', 'role_level'], 'verbose_name': 'IPC Role'},
        ),
        migrations.AlterModelOptions(
            name='rolegroup',
            options={'ordering': ['role_name'], 'verbose_name': 'IPC Role Group'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['zone_name'], 'verbose_name': 'IPC Zone'},
        ),
    ]
