# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_auto_20160219_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='parent_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Center'),
        ),
    ]
