# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-20 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_center_parent_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='parent_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Center'),
        ),
    ]
