# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 15:59
from __future__ import unicode_literals

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20160220_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('BR', 'Bramhachari'), ('FTT', 'Full Time Teacher'), ('PTT', 'Part Time Teacher'), ('FTV', 'Full Time Volunteer'), ('VOL', 'Volunteer'), ('STAFF', 'Staff'), ('SEV', 'Sevadhar')], default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='id_proof_scan',
            field=models.ImageField(blank=True, upload_to=contacts.models._generate_idproof_path),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('ACTV', 'Active'), ('INACTV', 'Inactive'), ('EXPD', 'Deceased')], max_length=6),
        ),
    ]
