# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0016_auto_20160225_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_category',
            field=models.CharField(choices=[('A', 'A Center'), ('B', 'B Center'), ('C', 'C Center')], default='A', max_length=1),
        ),
    ]
