# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_center_center_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualrole',
            name='admin_role',
            field=models.BooleanField(default=False),
        ),
    ]
