# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_individualrole_admin_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='primary_email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='primary Email'),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='note_type',
            field=models.CharField(choices=[('IN', 'Information Note'), ('SC', 'Status Change'), ('CN', 'Critical Note'), ('MN', 'Medical Note')], default='IN', max_length=2),
        ),
    ]
