# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_auto_20160424_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='pushover_token',
            field=models.CharField(blank=True, max_length=64, verbose_name='pushover Token'),
        ),
    ]
