# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_tag'),
        ('contacts', '0020_contact_pushover_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.Tag')),
            ],
            options={
                'ordering': ['contact', 'tag'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='contacttag',
            unique_together=set([('contact', 'tag')]),
        ),
    ]
