# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_auto_20161007_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='latitude',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='center',
            name='longitude',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
