# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_auto_20161126_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
