# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_auto_20171224_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='marital_status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('U', 'Unknown')], default='U', max_length=2),
        ),
    ]
