# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_contact_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='remarks',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='contactnote',
            name='note',
            field=models.TextField(max_length=500),
        ),
    ]
