# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0008_auto_20151212_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_title', models.CharField(blank=True, max_length=200, verbose_name='program title descriptive name')),
                ('program_code', models.CharField(blank=True, max_length=50, verbose_name='scheduling software program code')),
                ('program_code_source', models.CharField(blank=True, max_length=10, verbose_name='name of the scheduling software')),
                ('start_date', models.DateField()),
                ('program_type', models.CharField(blank=True, max_length=10, verbose_name='name of the program')),
                ('matched', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='was sync successful in matching a center')),
                ('match_confidence', models.PositiveSmallIntegerField()),
                ('match_overridden', models.CharField(choices=[('Y', 'Match Overridden'), ('N', 'System Match')], default='N', max_length=1, verbose_name='did admin override matched center')),
                ('remarks', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('new_records_added', models.IntegerField(default=0)),
                ('old_records_skipped', models.IntegerField(default=0)),
                ('matched_centers', models.IntegerField(default=0)),
            ],
        ),
    ]
