# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-start_date', '-program_code'], 'verbose_name': 'program schedule'},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ['-sync_date']},
        ),
        migrations.AddField(
            model_name='schedule',
            name='match_approved',
            field=models.CharField(choices=[('Y', 'Match Approved'), ('N', 'Match to be approved')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='match_overridden',
            field=models.CharField(choices=[('Y', 'Match Overridden'), ('N', 'System Match')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='matched',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='program_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='program_code_source',
            field=models.CharField(blank=True, max_length=10, verbose_name='scheduling software'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='program_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='program_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
