# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:06
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20151223_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='remarks',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
