# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ipctravels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0020_contact_pushover_token'),
        ('schedulemaster', '0017_programschedule_cancelled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtionalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(max_length=50, verbose_name='booked by')),
                ('purpose', models.CharField(max_length=50, verbose_name='Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='AgentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_journey', models.DateField()),
                ('source', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_of_booking', models.DateField(blank=True, null=True)),
                ('booked_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipctravels.AgentMaster')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetCodeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TicketDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, upload_to=ipctravels.models._generate_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='TravellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('non_ipc_contacts', models.CharField(blank=True, max_length=100, null=True)),
                ('fare', models.IntegerField(blank=True, null=True)),
                ('refund_amount', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('BK', 'Booked'), ('NB', 'Not booked'), ('CD', 'Cancelled')], default='BK', max_length=6)),
                ('budget_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipctravels.BudgetCodeMaster')),
            ],
        ),
        migrations.CreateModel(
            name='TravelModeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'New Request'), ('BK', 'Booked'), ('PB', 'Partially Booked'), ('CD', 'Cancelled'), ('PC', 'Partially Cancelled'), ('NP', 'Not processed')], default='NW', max_length=6)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('total_fare', models.IntegerField(blank=True, null=True)),
                ('cancellation_charge', models.IntegerField(blank=True, null=True)),
                ('refund_amount', models.IntegerField(blank=True, null=True)),
                ('request_mode', models.CharField(choices=[('SMS', 'SMS'), ('CL', 'Call'), ('EM', 'Email'), ('WA', 'Whatsapp'), ('OT', 'Others')], default='SMS', max_length=6, null=True)),
            ],
            options={
                'ordering': ['status'],
                'verbose_name': 'Ticket Request',
            },
        ),
        migrations.AddField(
            model_name='travellerdetails',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipctravels.TravelRequest'),
        ),
        migrations.AddField(
            model_name='travellerdetails',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='travellerdetails',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='travellerdetails',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone'),
        ),
        migrations.AddField(
            model_name='ticketdetails',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipctravels.TravelRequest'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipctravels.TravelRequest'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='travel_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipctravels.TravelModeMaster'),
        ),
        migrations.AddField(
            model_name='addtionaldetails',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipctravels.TravelRequest'),
        ),
    ]
