# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-11 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('ipctravels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtionaldetails',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='addtionaldetails',
            name='purpose',
        ),
        migrations.AddField(
            model_name='addtionaldetails',
            name='note',
            field=django_markdown.models.MarkdownField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='travellerdetails',
            name='purpose',
            field=models.CharField(choices=[('SC', 'Schedule'), ('BK', 'Break'), ('OA', 'Other Activities')], default='SC', max_length=6),
        ),
        migrations.AlterField(
            model_name='travellerdetails',
            name='status',
            field=models.CharField(choices=[('NB', 'NotBooked'), ('BK', 'Booked'), ('CD', 'Cancelled')], default='NB', max_length=6),
        ),
        migrations.AlterField(
            model_name='travellerdetails',
            name='traveller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
