# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipctravels', '0002_auto_20161011_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellerdetails',
            name='non_ipc_contacts',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
