# Generated by Django 2.0.4 on 2018-05-14 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_remove_contact_id_proof_other'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterMaterialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('sent_quantity', models.IntegerField(blank=True, null=True, verbose_name='Sent Quantity')),
            ],
            options={
                'verbose_name_plural': 'Center Materials',
                'verbose_name': 'Center Material',
            },
        ),
        migrations.CreateModel(
            name='CenterMaterialsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Center Materials Master',
            },
        ),
        migrations.CreateModel(
            name='ClassMaterialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('sent_quantity', models.IntegerField(blank=True, null=True, verbose_name='Sent Quantity')),
            ],
            options={
                'verbose_name_plural': 'Class Material',
                'verbose_name': 'Class Material',
            },
        ),
        migrations.CreateModel(
            name='ClassMaterialsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Class Materials Master',
            },
        ),
        migrations.CreateModel(
            name='ClassTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_box', models.SmallIntegerField(blank=True, null=True, verbose_name='No of box')),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['agency', 'sent_date'],
                'verbose_name': 'Courier Detail',
            },
        ),
        migrations.CreateModel(
            name='KitsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('sent_quantity', models.IntegerField(blank=True, null=True, verbose_name='Sent Quantity')),
            ],
            options={
                'verbose_name_plural': 'Kits',
                'verbose_name': 'Kit',
            },
        ),
        migrations.CreateModel(
            name='KitsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Kits Master',
            },
        ),
        migrations.CreateModel(
            name='MaterialsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='Expected Delivery Date')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('center', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='zone', null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('class_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ClassTypeMaster', verbose_name='Class Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Materials Request',
                'verbose_name': 'Material Request',
            },
        ),
        migrations.CreateModel(
            name='MaterialStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherMaterialsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Other - Event Materials Master',
            },
        ),
        migrations.CreateModel(
            name='OtherMaterialsMasterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('sent_quantity', models.IntegerField(blank=True, null=True, verbose_name='Sent Quantity')),
                ('brochures_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialsRequest')),
                ('other_materials', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.OtherMaterialsMaster')),
            ],
            options={
                'verbose_name_plural': 'Other Material Items',
                'verbose_name': 'Other Material Item',
            },
        ),
        migrations.AddField(
            model_name='materialsrequest',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialTypeMaster', verbose_name='Material Type'),
        ),
        migrations.AddField(
            model_name='materialsrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialStatusMaster', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='materialsrequest',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='kitsitem',
            name='brochures_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialsRequest'),
        ),
        migrations.AddField(
            model_name='kitsitem',
            name='kits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.KitsMaster'),
        ),
        migrations.AddField(
            model_name='courierdetails',
            name='accounts_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialsRequest'),
        ),
        migrations.AddField(
            model_name='classmaterialsmaster',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.ClassTypeMaster', verbose_name='Class Type'),
        ),
        migrations.AddField(
            model_name='classmaterialitem',
            name='brochures_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialsRequest'),
        ),
        migrations.AddField(
            model_name='classmaterialitem',
            name='class_materials',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='class_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.ClassMaterialsMaster'),
        ),
        migrations.AddField(
            model_name='centermaterialitem',
            name='brochures_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialsRequest'),
        ),
        migrations.AddField(
            model_name='centermaterialitem',
            name='center_materials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.CenterMaterialsMaster'),
        ),
        migrations.CreateModel(
            name='MaterialsRequestIncharge',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'verbose_name': 'Materials Incharge',
            },
            bases=('materials.materialsrequest',),
        ),
        migrations.AlterUniqueTogether(
            name='classmaterialsmaster',
            unique_together={('name', 'class_type')},
        ),
    ]
