# Generated by Django 2.0.4 on 2018-05-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Materials Note',
            },
        ),
        migrations.RemoveField(
            model_name='materialsrequest',
            name='remarks',
        ),
        migrations.AddField(
            model_name='materialnotes',
            name='material_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.MaterialsRequest'),
        ),
    ]
