# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 11:13
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeritemnotes',
            name='note',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationtransaction',
            name='donation_remarks',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='description',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='payment_remarks',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='transactionnotes',
            name='note',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
