# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_merge'),
        ('materials', '0002_auto_20160106_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsCenter',
            fields=[
            ],
            options={
                'verbose_name': 'Material for Center',
                'proxy': True,
            },
            bases=('contacts.center',),
        ),
    ]
