# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-11 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialscenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centermaterial',
            options={'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='centermaterial',
            name='remarks',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
