# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20160411_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='centermaterial',
            name='accounting_year',
            field=models.CharField(blank=True, choices=[('2000/01', '2000/01'), ('2001/02', '2001/02'), ('2002/03', '2002/03'), ('2003/04', '2003/04'), ('2004/05', '2004/05'), ('2005/06', '2005/06'), ('2006/07', '2006/07'), ('2007/08', '2007/08'), ('2008/09', '2008/09'), ('2009/10', '2009/10'), ('2010/11', '2010/11'), ('2011/12', '2011/12'), ('2012/13', '2012/13'), ('2013/14', '2013/14'), ('2014/15', '2014/15'), ('2015/16', '2015/16'), ('2016/17', '2016/17')], max_length=10),
        ),
        migrations.AddField(
            model_name='centermaterial',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='centermaterial',
            name='date_of_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='centermaterial',
            name='fixed_asset_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='centermaterial',
            name='vendor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
