# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-26 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_auto_20161226_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centermaterial',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='centermaterial',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
