# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_auto_20161226_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centeritemnotes',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationtransaction',
            name='donation_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemmaster',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchasetransaction',
            name='payment_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transactionnotes',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
