# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-29 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0024_auto_20171224_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='AshramVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival Date & Time')),
                ('departure_time', models.TimeField(verbose_name='Departure Time')),
                ('participant_count', models.IntegerField()),
                ('lunch', models.BooleanField()),
                ('dinner', models.BooleanField()),
                ('contact_person', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('Center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
            ],
        ),
    ]
