# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 16:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ashramvisit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ashramvisit',
            name='Center',
            field=smart_selects.db_fields.GroupedForeignKey(group_field='zone', on_delete=django.db.models.deletion.CASCADE, to='contacts.Center'),
        ),
    ]
