# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', django_markdown.models.MarkdownField(blank=True, max_length=500, verbose_name='Why is this communication being sent (Include Approver name)')),
                ('communication_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=6)),
                ('subject', models.CharField(max_length=200)),
                ('message', django_markdown.models.MarkdownField(blank=True)),
            ],
        ),
    ]
