# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0002_auto_20160219_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailer',
            name='exclude_list',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailer',
            name='include_list',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailer',
            name='communication_type',
            field=models.CharField(max_length=200),
        ),
    ]
