# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0003_auto_20160219_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='include_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
    ]
