# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iconnect', '0004_auto_20160219_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='include_list',
            field=models.CharField(max_length=200),
        ),
    ]
