# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedulemaster', '0025_programschedule_created'),
        ('contacts', '0023_center_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NP Vouchers Type Master',
            },
        ),
        migrations.CreateModel(
            name='AccountTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Type Master',
            },
        ),
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['agency', 'sent_date'],
                'verbose_name': 'Courier Detail',
            },
        ),
        migrations.CreateModel(
            name='EntityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountTypeMaster')),
            ],
            options={
                'verbose_name': 'Expense master',
            },
        ),
        migrations.CreateModel(
            name='NPVoucherStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountType')),
            ],
            options={
                'verbose_name': 'NP Voucher Status Master',
            },
        ),
        migrations.CreateModel(
            name='RCOAccountsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('AO', 'Open'), ('CL', 'Closed'), ('CA', 'Cancelled')], default='AO', max_length=2)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountTypeMaster')),
                ('entity_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.EntityMaster')),
                ('program_schedule', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='program', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone')),
            ],
            options={
                'ordering': ['account_type', 'entity_name'],
                'verbose_name': 'RCO Voucher Approval Tracking',
            },
        ),
        migrations.CreateModel(
            name='RCOVoucherStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RCO Voucher Status Master',
            },
        ),
        migrations.CreateModel(
            name='TransactionNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_markdown.models.MarkdownField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accounts_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Transaction Note',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=100)),
                ('voucher_date', models.DateField()),
                ('expenses_description', models.CharField(blank=True, max_length=100)),
                ('party_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('approval_sent_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('finance_submission_date', models.DateField(blank=True, null=True)),
                ('movement_sheet_no', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('utr_no', models.CharField(blank=True, max_length=100, verbose_name='UTR NO')),
                ('amount_after_tds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount after TDS')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accounts_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster')),
                ('head_of_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.ExpensesTypeMaster', verbose_name='Head of Expenses')),
            ],
            options={
                'ordering': ['nature_of_voucher'],
                'verbose_name': 'Voucher',
            },
        ),
        migrations.CreateModel(
            name='VoucherMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='nature_of_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.VoucherMaster'),
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='np_voucher_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.NPVoucherStatusMaster'),
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='voucher_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOVoucherStatusMaster'),
        ),
        migrations.AddField(
            model_name='courierdetails',
            name='accounts_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster'),
        ),
        migrations.CreateModel(
            name='NPAccountsMaster',
            fields=[
            ],
            options={
                'verbose_name': 'NP Voucher Approval Tracking',
                'proxy': True,
            },
            bases=('ipcaccounts.rcoaccountsmaster',),
        ),
    ]
