# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-14 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models
import ipcaccounts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0023_center_city'),
        ('schedulemaster', '0025_programschedule_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('TEACH', 'Teachers Accounts'), ('CLASS', 'Class Accounts'), ('OTHER   ', 'Other Accounts')], default='CLASS', max_length=6)),
                ('tracking_no', models.CharField(default=ipcaccounts.models.increment_tracking_number, max_length=100)),
                ('voucher_date', models.DateField(blank=True, null=True)),
                ('head_of_expenses', models.CharField(max_length=100, null=True)),
                ('budget_code', models.CharField(blank=True, max_length=100, null=True)),
                ('expenses_description', models.CharField(blank=True, max_length=100, null=True)),
                ('party_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approval_sent_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('approval_status', models.CharField(blank=True, choices=[('MAIL', 'Mail Approved'), ('PHY', 'Physically Approved')], default='MAIL', max_length=6)),
                ('finance_submission_date', models.DateField(blank=True, null=True)),
                ('movement_sheet_no', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('utr_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='UTR NO')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
            ],
        ),
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_no', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('remarks', django_markdown.models.MarkdownField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accounts_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountsMaster')),
            ],
        ),
        migrations.CreateModel(
            name='EntityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', django_markdown.models.MarkdownField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accounts_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountsMaster')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VoucherMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='entity_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.EntityMaster'),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='nature_of_voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.VoucherMaster'),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='program_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='accountsmaster',
            name='voucher_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.VoucherStatusMaster'),
        ),
    ]
