# Generated by Django 2.0.4 on 2018-04-13 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('schedulemaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'NP Vouchers Type Master',
            },
        ),
        migrations.CreateModel(
            name='AccountTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Type Master',
            },
        ),
        migrations.CreateModel(
            name='CourierDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Courier Detail',
                'ordering': ['agency', 'sent_date'],
            },
        ),
        migrations.CreateModel(
            name='EntityMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountTypeMaster')),
            ],
            options={
                'verbose_name': 'Expense master',
            },
        ),
        migrations.CreateModel(
            name='NPVoucherStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountType')),
            ],
            options={
                'verbose_name': 'NP Voucher Status Master',
            },
        ),
        migrations.CreateModel(
            name='RCOAccountsMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_code', models.CharField(blank=True, max_length=100)),
                ('voucher_date', models.DateField(default=datetime.date.today, verbose_name='Voucher Date')),
                ('approval_sent_date', models.DateField(blank=True, null=True, verbose_name='Approval request Date')),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('finance_submission_date', models.DateField(blank=True, null=True)),
                ('movement_sheet_no', models.CharField(blank=True, max_length=100)),
                ('email_sent', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountTypeMaster', verbose_name='Account Type')),
                ('entity_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.EntityMaster', verbose_name='Entity')),
                ('np_voucher_status', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.NPVoucherStatusMaster', verbose_name='NP Voucher Status')),
                ('program_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster', verbose_name='Program Type')),
            ],
            options={
                'verbose_name': 'RCO Voucher',
                'ordering': ['account_type', 'entity_name'],
            },
        ),
        migrations.CreateModel(
            name='RCOVoucherStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'RCO Voucher Status Master',
            },
        ),
        migrations.CreateModel(
            name='TransactionNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accounts_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster')),
            ],
            options={
                'verbose_name': 'Transaction Note',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('ADD', 'Add Treasurer'), ('CHG', 'Change Treasurer')], default='ADD', max_length=3)),
                ('ifsc_code', models.CharField(max_length=15, verbose_name='IFSCode')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('account_holder', models.CharField(max_length=50, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=15, verbose_name='Account Number')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('center', smart_selects.db_fields.GroupedForeignKey(group_field='zone', on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('new_treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_treasurer', to='contacts.Contact')),
                ('old_treasurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_treasurer', to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'Treasurer',
            },
        ),
        migrations.CreateModel(
            name='VoucherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(blank=True, max_length=100)),
                ('voucher_type', models.CharField(choices=[('BV', 'Bank Voucher'), ('CV', 'Cash Voucher'), ('JV', 'Journal Voucher')], default='BV', max_length=2)),
                ('expenses_description', models.CharField(blank=True, max_length=100)),
                ('party_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('utr_no', models.CharField(blank=True, max_length=100, verbose_name='UTR NO')),
                ('tds_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='TDS Amount')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accounts_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster')),
                ('head_of_expenses', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.ExpensesTypeMaster', verbose_name='Head of Expenses')),
            ],
            options={
                'verbose_name': 'Voucher',
                'ordering': ['tracking_no', 'nature_of_voucher'],
            },
        ),
        migrations.CreateModel(
            name='VoucherMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='voucherdetails',
            name='nature_of_voucher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.VoucherMaster'),
        ),
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='rco_voucher_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOVoucherStatusMaster', verbose_name='RCO Voucher Status'),
        ),
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact'),
        ),
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='courierdetails',
            name='accounts_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOAccountsMaster'),
        ),
        migrations.CreateModel(
            name='NPAccountsMaster',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'NP Voucher',
                'indexes': [],
            },
            bases=('ipcaccounts.rcoaccountsmaster',),
        ),
        migrations.AlterUniqueTogether(
            name='expensestypemaster',
            unique_together={('name', 'type')},
        ),
    ]
