# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-21 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetails',
            name='amount_after_tds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Amount after TDS'),
        ),
    ]
