# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 06:28
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdetails',
            name='head_of_expenses',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.ExpensesTypeMaster', verbose_name='Head of Expenses'),
        ),
        migrations.AlterField(
            model_name='voucherdetails',
            name='np_voucher_status',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.NPVoucherStatusMaster'),
        ),
    ]
