# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-06 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classexpensestypemaster',
            options={'verbose_name': 'Class Expense'},
        ),
        migrations.AlterModelOptions(
            name='courierdetails',
            options={'ordering': ['agency', 'sent_date'], 'verbose_name': 'Courier Detail'},
        ),
        migrations.AlterModelOptions(
            name='teacherexpensestypemaster',
            options={'verbose_name': 'Teacher Expense'},
        ),
    ]
