# Generated by Django 2.0.5 on 2018-06-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='budget_code',
            field=models.CharField(default='No Budget Code given', max_length=100),
        ),
    ]
