# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0002_auto_20171206_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherstatusmaster',
            options={'verbose_name': 'Voucher Status Master'},
        ),
        migrations.RenameField(
            model_name='courierdetails',
            old_name='tracking_no',
            new_name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='accountsmaster',
            name='center',
        ),
        migrations.RemoveField(
            model_name='courierdetails',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='courierdetails',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='courierdetails',
            name='source',
        ),
        migrations.RemoveField(
            model_name='voucherdetails',
            name='approval_status',
        ),
        migrations.AddField(
            model_name='voucherstatusmaster',
            name='type',
            field=models.CharField(blank=True, choices=[('RC', 'RCO'), ('NP', 'Nodal Point'), ('FI', 'Finance')], default='RC', max_length=2),
        ),
        migrations.AlterField(
            model_name='voucherdetails',
            name='delayed_approval',
            field=models.BooleanField(default=False, verbose_name='Delay Approval'),
        ),
    ]
