# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0002_auto_20180118_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherdetails',
            options={'ordering': ['tracking_no', 'nature_of_voucher'], 'verbose_name': 'Voucher'},
        ),
    ]
