# Generated by Django 2.0.5 on 2018-06-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0002_auto_20180614_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='budget_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
