# Generated by Django 2.0.4 on 2018-06-15 07:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0003_auto_20180614_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='audit_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='notify_meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='notify_toggle',
            field=models.BooleanField(default=False),
        ),
    ]
