# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0003_auto_20180314_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherdetails',
            name='voucher_type',
            field=models.CharField(choices=[('BV', 'Bank Voucher'), ('CV', 'Cash Voucher'), ('JV', 'Journal Voucher')], default='BV', max_length=2),
        ),
    ]
