# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-27 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0005_auto_20180327_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountTypeMaster'),
        ),
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='approval_sent_date',
            field=models.DateField(blank=True, null=True, verbose_name='Approval request Date'),
        ),
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='entity_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.EntityMaster'),
        ),
    ]
