# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0006_auto_20180327_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherdetails',
            name='nature_of_voucher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.VoucherMaster'),
        ),
    ]
