# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0024_auto_20171224_1428'),
        ('ipcaccounts', '0007_auto_20180328_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc_code', models.CharField(max_length=15, verbose_name='IFSCode')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('branch_name', models.CharField(max_length=100, verbose_name='Branch Name')),
                ('account_holder', models.CharField(max_length=50, verbose_name='Account Holder Name')),
                ('account_number', models.CharField(max_length=15, verbose_name='Account Number')),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Center')),
                ('new_treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_treasurer', to='contacts.Contact')),
                ('old_treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_treasurer', to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'Treasurer Change Request',
            },
        ),
    ]
