# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0009_treasurer_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='old_treasurer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_treasurer', to='contacts.Contact'),
        ),
    ]
