# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0010_auto_20180331_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurer',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
