# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0011_auto_20180331_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treasurer',
            options={'verbose_name': 'Treasurer'},
        ),
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
