# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0013_auto_20180331_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensestypemaster',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='expensestypemaster',
            unique_together=set([('name', 'type')]),
        ),
    ]
