# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-03 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0014_auto_20180403_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.AccountTypeMaster', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='entity_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.EntityMaster', verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='np_voucher_status',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='type', null=True, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.NPVoucherStatusMaster', verbose_name='NP Voucher Status'),
        ),
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='rco_voucher_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ipcaccounts.RCOVoucherStatusMaster', verbose_name='RCO Voucher Status'),
        ),
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Zone', verbose_name='Zone'),
        ),
    ]
