# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-04 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0015_auto_20180403_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierdetails',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
