# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemaster', '0031_auto_20180328_1418'),
        ('ipcaccounts', '0017_auto_20180408_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcoaccountsmaster',
            name='program_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramMaster', verbose_name='Program Type'),
        ),
    ]
