# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-08 11:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0018_rcoaccountsmaster_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcoaccountsmaster',
            name='program_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedulemaster.ProgramSchedule'),
        ),
    ]
