# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0019_auto_20180408_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npaccountsmaster',
            options={'verbose_name': 'NP Voucher'},
        ),
        migrations.AlterModelOptions(
            name='rcoaccountsmaster',
            options={'ordering': ['account_type', 'entity_name'], 'verbose_name': 'RCO Voucher'},
        ),
    ]
