# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipcaccounts', '0020_auto_20180411_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionnotes',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
